# Generated by Django 3.2.7 on 2021-09-12 17:39

import Profile_Album.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('Album_Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Album_Name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('Album_Description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Photo_Album_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to=Profile_Album.models.photo_path)),
                ('_Album_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='All_data', to='Profile_Album.photo')),
            ],
        ),
    ]
